<div class="container">
    <div class="row">
        <div class="span6 offset3 landing-header">
                <h1>IGN Pokedex</h1>
        </div>
    </div>
    <div class="row">
        <div class="span6 offset3">
            <form class="well form-search" method="post" action="">
                <input type="text" placeholder="Input Pokemon name or ID" name="name" id="name" class="input-medium search-query span4">
                <button type="submit" class="btn pull-right">Search</button>
            </form>
        </div>
    </div>
</div>

