<div class="container">
    <ul class="nav nav-pills pkm-number-nav">
        <li class="pull-left"><a href="#">#24 Arbok</a></li>
        <li class="span4 offset4 pkm-current"><a href="#">Pikachu</a></li>
        <li class="pull-right"><a href="#">#26 Raichu</a></li>
    </ul>
</div>

<div class="container pkm-form">
    <div class="row">
        <div class="span3 pkm-profile-pic thumbnail"><img src="http://placehold.it/260x180" alt="pkm-profile-pic"></div>
        <div class="span8">
            <p>Editorial Description:
            Lorem ipsum dolor sit amet, maiores ornare ac fermentum, imperdiet ut vivamus a, nam lectus at nunc. Quam euismod sem, semper ut potenti pellentesque quisque. In eget sapien sed, sit duis vestibulum ultricies, placerat morbi amet vel, nullam in in lorem vel.
            </p>
        </div>
    </div>
    <div class="row">
        <div class="span3">
            <div class="btn-group">
                <a href="#" class="btn btn-mini">Thumbs Up</a>
                <a href="#" class="btn btn-mini">Thumbs Down</a>
            </div>
        </div>
        <div class="span8">
            <table class="table table-striped table-bordered table-condensed">
                <tr><td class="span2">Number</td><td></td></tr>
                <tr><td>Type</td><td></td></tr>
                <tr><td>Egg Group</td><td></td></tr>
                <tr><td>Gender</td><td></td></tr>
                <tr><td>Weakness</td><td></td></tr>
                <tr><td>Height</td><td></td></tr>
                <tr><td>Weight</td><td></td></tr>
            </table>
        </div>
    </div>
</div>
<div class="page-header pkm-section-header">
    <h2>Evolution</h2>
</div>
<div class="container evolution">
    <div class="row">
        <div class="span2 ">
            <a href="#"><img src="http://placehold.it/260x180" alt="name of pokemon"></a>
            <br>
            <a href="#" class="pkm-name">Pichu</a>
            <br>
            #172
            <br>
            <a href="#" class="pkm-type">Electric</a>
        </div>
        <div class="span2 arrow">
            <em>&rarr;</em>
            <br>
            <span class="pkm-evo-how">by Happiness</span>
        </div>
        <div class="span2">
            <a href="#"><img src="http://placehold.it/260x180" alt="name of pokemon"></a>
            <br>
            <a href="#" class="pkm-name">Pikachu</a>
            <br>
            #25
            <br>
            <a href="#" class="pkm-type">Electric</a>
        </div>
        <div class="span2">
            <em>&rarr;</em>
            <br>
            <span class="pkm-evo-how">use Thunderstone</span>
        </div>
        <div class="span2">
            <a href="#"><img src="http://placehold.it/260x180" alt="name of pokemon"></a>
            <br>
            <a href="#" class="pkm-name">Raichu</a>
            <br>
            #26
            <br>
            <a href="#" class="pkm-type">Electric</a>
        </div>
    </div>
</div>

<div class="page-header pkm-section-header">
    <h2>Moves</h2>
</div>
<div class="container">
    <div class="row">
        <div class="span 10">
            <div class="tabbable">
                <ul class="nav nav-tabs" id="moveTab">
                    <li class=""><a href="#level-moves" data-toggle="tab">Level Moves</a></li>
                    <li class=""><a href="#hm-tm-moves" data-toggle="tab">HM & TM</a></li>
                    <li class=""><a href="#move-tutor-moves" data-toggle="tab">Move Tutor Moves</a></li>
                </ul>
                <div class="tab-content pkm-move-list span10">
                    <div class="tab-pane" id="level-moves">
                        <table class="table table-striped table-bordered table-condensed">
                            <thead>
                                <tr><th>Level</th><th>Move</th><th>Type</th></tr>
                            </thead>
                            <tbody>
                                <tr><td class="span2">Number</td><td></td><td></td></tr>
                                <tr><td>Type</td><td></td><td></td></tr>
                                <tr><td>Egg Group</td><td></td><td></td></tr>
                                <tr><td>Gender</td><td></td><td></td></tr>
                                <tr><td>Weakness</td><td></td><td></td></tr>
                                <tr><td>Height</td><td></td><td></td></tr>
                                <tr><td>Weight</td><td></td><td></td></tr>
                            </tbody>

                        </table>
                    </div>
                    <div class="tab-pane" id="hm-tm-moves">
                        <h3>Moves by HM</h3>
                        <table class="table table-striped table-bordered table-condensed">
                            <thead>
                            <tr><th>Level</th><th>Move</th><th>Type</th></tr>
                            </thead>
                            <tbody>
                            <tr><td class="span2">Number</td><td></td><td></td></tr>
                            <tr><td>Type</td><td></td><td></td></tr>
                            <tr><td>Egg Group</td><td></td><td></td></tr>
                            <tr><td>Gender</td><td></td><td></td></tr>
                            <tr><td>Weakness</td><td></td><td></td></tr>
                            <tr><td>Height</td><td></td><td></td></tr>
                            <tr><td>Weight</td><td></td><td></td></tr>
                            </tbody>
                        </table>
                        <h3>Moves by TM</h3>
                        <table class="table table-striped table-bordered table-condensed">
                            <thead>
                            <tr><th>Level</th><th>Move</th><th>Type</th></tr>
                            </thead>
                            <tbody>
                            <tr><td class="span2">Number</td><td></td><td></td></tr>
                            <tr><td>Type</td><td></td><td></td></tr>
                            <tr><td>Egg Group</td><td></td><td></td></tr>
                            <tr><td>Gender</td><td></td><td></td></tr>
                            <tr><td>Weakness</td><td></td><td></td></tr>
                            <tr><td>Height</td><td></td><td></td></tr>
                            <tr><td>Weight</td><td></td><td></td></tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="tab-pane" id="move-tutor-moves">
                        <table class="table table-striped table-bordered table-condensed">
                            <tr><td class="span2">Number</td><td></td><td></td></tr>
                            <tr><td>Type</td><td></td><td></td></tr>
                            <tr><td>Egg Group</td><td></td><td></td></tr>
                            <tr><td>Gender</td><td></td><td></td></tr>
                            <tr><td>Weakness</td><td></td><td></td></tr>
                            <tr><td>Height</td><td></td><td></td></tr>
                            <tr><td>Weight</td><td></td><td></td></tr>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="span7">
            <div class="page-header pkm-section-header">
                <h2>Type Defense</h2>
            </div>
            <table class="table table-striped table-bordered table-condensed table-type-defense">
                <thead>
                    <tr>
                        <th>NOR</th>
                        <th>FIR</th>
                        <th>WAT</th>
                        <th>ELE</th>
                        <th>GRA</th>
                        <th>ICE</th>
                        <th>FIG</th>
                        <th>POI</th>
                        <th>GRO</th>
                        <th>FLY</th>
                        <th>PSY</th>
                        <th>BUG</th>
                        <th>ROC</th>
                        <th>GHO</th>
                        <th>DRA</th>
                        <th>DAR</th>
                        <th>STE</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
            <div class="page-header pkm-section-header">
                <h2>Location</h2>
            </div>
            <table class="table table-striped table-bordered table-condensed table-location">
              <tbody>                     
                    <tr>
                        <th>
                            Red
                            <br>
                            Blue 
                        </th>
                        <td>
                        </td>
                    </tr>
                    <tr><th></th><td></td></tr>
                    <tr><th></th><td></td></tr>
                    <tr><th></th><td></td></tr>
                    <tr><th></th><td></td></tr>
                    <tr><th></th><td></td></tr>
                    <tr><th></th><td></td></tr>
                    <tr><th></th><td></td></tr>
                    <tr><th></th><td></td></tr>
                    <tr><th></th><td></td></tr>
                    <tr><th></th><td></td></tr>
               </tbody>
            </table>
        </div>
        <div class="span5">
            <div class="page-header pkm-section-header">
                <h2>Stats</h2>
            </div>
            <table class="table table-striped table-bordered table-condensed table-stats">
                <tbody>
                <tr>
                    <th>HP</th>
                    <td class="pkm-numeric">35</td>
                    <td class="pkm-bar-graph">
                        <div class="progress">
                            <div class="bar" style="width: 35%;"></div>
                        </div>
                    </td>
                </tr>
                <tr><th></th><td></td><td></td></tr>
                <tr><th></th><td></td><td></td></tr>
                <tr><th></th><td></td><td></td></tr>
                <tr><th></th><td></td><td></td></tr>
                <tr><th></th><td></td><td></td></tr>
                <tr><th></th><td></td><td></td></tr>
                <tr><th></th><td></td><td></td></tr>
                <tr><th></th><td></td><td></td></tr>
                <tr><th></th><td></td><td></td></tr>
                <tr><th></th><td></td><td></td></tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<p>View script for controller <b>Pokedex</b> and script/action name <b>index</b></p>
