<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->headLink()->appendStylesheet('/css/bootstrap.css')->appendStylesheet('/css/pokedex.css')?>
  <?php echo $this->headScript()->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js')->appendFile('/js/bootstrap.js')->appendFile('/js/bootstrap-tab.js')->appendFile('/js/pokedex.js')?>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="<?php echo $this->url(array('controller'=>'pokedex','action'=>'index'),null, true); ?>">IGN Pokedex</a>
                <ul class="nav">
                    <li><a href="<?php echo $this->url(array('controller'=>'pokedex','action'=>'browse'), null, true); ?>">Browse</a></li>
                    <li><a href="<?php echo $this->url(array('controller'=>'pokedex','action'=>'comparison'), null, true); ?>">Comparison</a></li>
                    <li><a href="<?php echo $this->url(array('controller'=>'pokedex','action'=>'maps'), null, true); ?>">Maps</a></li>
                </ul>
                <form class="navbar-search pull-right" id="nav-search" method="post" action="http://localhost:8888/pokedex/index">
                    <input type="text" class="search-query"  name="name" placeholder="Search by name or ID">
                    <button type="submit" class="btn">Search</button>
                </form>
            </div>
        </div>
    </div>
    <div class="container container-content-main">
        <div class="view-content">
            <?php echo $this->layout()->content ?>
        </div>
    </div>

    <div class="footer">
        <div class="footer-content">
                <p class="credit">By Team Super Effective 2012</p>
        </div>
    </div>

 
</body>
</html>
